In [ ]:
import pandas as pd

In [ ]:
data2020 = pd.read_csv("./2020_survey_results_public.csv")
data2019 = pd.read_csv("./2019_survey_results_public.csv")
data2018 = pd.read_csv("./2018_survey_results_public.csv")

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (8,12,13,14,15,16,50,51,52,53,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [ ]:
data2018.head()

   Respondent Hobby  ...                         SurveyTooLong     SurveyEasy
0           1   Yes  ...  The survey was an appropriate length      Very easy
1           3   Yes  ...  The survey was an appropriate length  Somewhat easy
2           4   Yes  ...                                   NaN            NaN
3           5    No  ...  The survey was an appropriate length  Somewhat easy
4           7   Yes  ...  The survey was an appropriate length  Somewhat easy

[5 rows x 129 columns]

target features: `ConvertedComp`(2019, 2020),`ConvertedSalary` (2018)

- 2020, 2019: `Hobbyist` vs. 2018: `Hobby`
- 2020, 2019: `OrgSize` vs. 2018: `CompanySize`
- 2020, 2019: `JobSat` vs. 2018: `JobSatisfaction`
- 2020, 2019: `YearsCode`, `YearsCodePro` (natural number) vs. 2018: `YearsCoding`, `YearsCodingProf` (range)
- 2020, 2019: `EdLevel` vs. 2018: `FormalEducation`
- 2020, 2019: `JobSeek` vs. 2018: `JobSearchStatus`
- 2020, 2019: `Ethnicity` vs. 2018: `RaceEthnicity`
- 2020, 2019: `OpSys` vs. 2018: `OperatingSystem`

In [ ]:
data2018.rename(columns = {'Hobby' : 'Hobbyist'}, inplace = True)
data2018.rename(columns = {'CompanySize' : 'OrgSize'}, inplace = True)
data2018.rename(columns = {'JobSatisfaction' : 'JobSat'}, inplace = True)
data2018.rename(columns = {'YearsCoding' : 'YearsCode'}, inplace = True)
data2018.rename(columns = {'YearsCodingProf ' : 'YearsCodePro '}, inplace = True)
data2018.rename(columns = {'FormalEducation' : 'EdLevel'}, inplace = True)
data2018.rename(columns = {'JobSearchStatus' : 'JobSeek '}, inplace = True)
data2018.rename(columns = {'RaceEthnicity' : 'Ethnicity'}, inplace = True)
data2018.rename(columns = {'OperatingSystem' : 'OpSys '}, inplace = True)

In [ ]:
columns2020 = data2020.columns
print(columns2020)
print(len(columns2020))

Index(['Respondent', 'MainBranch', 'Hobbyist', 'Age', 'Age1stCode', 'CompFreq',
       'CompTotal', 'ConvertedComp', 'Country', 'CurrencyDesc',
       'CurrencySymbol', 'DatabaseDesireNextYear', 'DatabaseWorkedWith',
       'DevType', 'EdLevel', 'Employment', 'Ethnicity', 'Gender', 'JobFactors',
       'JobSat', 'JobSeek', 'LanguageDesireNextYear', 'LanguageWorkedWith',
       'MiscTechDesireNextYear', 'MiscTechWorkedWith',
       'NEWCollabToolsDesireNextYear', 'NEWCollabToolsWorkedWith', 'NEWDevOps',
       'NEWDevOpsImpt', 'NEWEdImpt', 'NEWJobHunt', 'NEWJobHuntResearch',
       'NEWLearn', 'NEWOffTopic', 'NEWOnboardGood', 'NEWOtherComms',
       'NEWOvertime', 'NEWPurchaseResearch', 'NEWPurpleLink', 'NEWSOSites',
       'NEWStuck', 'OpSys', 'OrgSize', 'PlatformDesireNextYear',
       'PlatformWorkedWith', 'PurchaseWhat', 'Sexuality', 'SOAccount',
       'SOComm', 'SOPartFreq', 'SOVisitFreq', 'SurveyEase', 'SurveyLength',
       'Trans', 'UndergradMajor', 'WebframeDesireNextYear',
       'WebframeWorkedWith', 'WelcomeChange', 'WorkWeekHrs', 'YearsCode',
       'YearsCodePro'],
      dtype='object')
61

In [ ]:
columns2019 = data2019.columns
print(columns2019)
print(len(columns2019))

Index(['Respondent', 'MainBranch', 'Hobbyist', 'OpenSourcer', 'OpenSource',
       'Employment', 'Country', 'Student', 'EdLevel', 'UndergradMajor',
       'EduOther', 'OrgSize', 'DevType', 'YearsCode', 'Age1stCode',
       'YearsCodePro', 'CareerSat', 'JobSat', 'MgrIdiot', 'MgrMoney',
       'MgrWant', 'JobSeek', 'LastHireDate', 'LastInt', 'FizzBuzz',
       'JobFactors', 'ResumeUpdate', 'CurrencySymbol', 'CurrencyDesc',
       'CompTotal', 'CompFreq', 'ConvertedComp', 'WorkWeekHrs', 'WorkPlan',
       'WorkChallenge', 'WorkRemote', 'WorkLoc', 'ImpSyn', 'CodeRev',
       'CodeRevHrs', 'UnitTests', 'PurchaseHow', 'PurchaseWhat',
       'LanguageWorkedWith', 'LanguageDesireNextYear', 'DatabaseWorkedWith',
       'DatabaseDesireNextYear', 'PlatformWorkedWith',
       'PlatformDesireNextYear', 'WebFrameWorkedWith',
       'WebFrameDesireNextYear', 'MiscTechWorkedWith',
       'MiscTechDesireNextYear', 'DevEnviron', 'OpSys', 'Containers',
       'BlockchainOrg', 'BlockchainIs', 'BetterLife', 'ITperson', 'OffOn',
       'SocialMedia', 'Extraversion', 'ScreenName', 'SOVisit1st',
       'SOVisitFreq', 'SOVisitTo', 'SOFindAnswer', 'SOTimeSaved',
       'SOHowMuchTime', 'SOAccount', 'SOPartFreq', 'SOJobs', 'EntTeams',
       'SOComm', 'WelcomeChange', 'SONewContent', 'Age', 'Gender', 'Trans',
       'Sexuality', 'Ethnicity', 'Dependents', 'SurveyLength', 'SurveyEase'],
      dtype='object')
85

In [ ]:
columns2018 = data2018.columns
print(columns2018)
print(len(columns2018))
print(data2018.head())

Index(['Respondent', 'Hobbyist', 'OpenSource', 'Country', 'Student',
       'Employment', 'EdLevel', 'UndergradMajor', 'OrgSize', 'DevType',
       ...
       'Exercise', 'Gender', 'SexualOrientation', 'EducationParents',
       'Ethnicity', 'Age', 'Dependents', 'MilitaryUS', 'SurveyTooLong',
       'SurveyEasy'],
      dtype='object', length=129)
129
   Respondent Hobbyist  ...                         SurveyTooLong     SurveyEasy
0           1      Yes  ...  The survey was an appropriate length      Very easy
1           3      Yes  ...  The survey was an appropriate length  Somewhat easy
2           4      Yes  ...                                   NaN            NaN
3           5       No  ...  The survey was an appropriate length  Somewhat easy
4           7      Yes  ...  The survey was an appropriate length  Somewhat easy

[5 rows x 129 columns]

In [ ]:
final_2018 = pd.DataFrame([])
final_2019 = pd.DataFrame([])
final_2020 = pd.DataFrame([])

## LanguageWorkedWith

In [ ]:
total_languages = []

In [ ]:
language2018 = data2018['LanguageWorkedWith']

languages2018 = []

for row in language2018:
  for lang in str(row).split(';'):
    if lang not in languages2018:
      languages2018.append(lang)
    if lang not in total_languages:
      total_languages.append(lang)

print(languages2018)
print(len(languages2018))

['JavaScript', 'Python', 'HTML', 'CSS', 'Bash/Shell', 'nan', 'C#', 'SQL', 'TypeScript', 'C', 'C++', 'Java', 'Matlab', 'R', 'Assembly', 'CoffeeScript', 'Erlang', 'Go', 'Lua', 'Ruby', 'PHP', 'VB.NET', 'Swift', 'Groovy', 'Kotlin', 'Objective-C', 'Scala', 'F#', 'Haskell', 'Rust', 'Julia', 'VBA', 'Perl', 'Cobol', 'Visual Basic 6', 'Delphi/Object Pascal', 'Hack', 'Clojure', 'Ocaml']
39

In [ ]:
language2019 = data2019['LanguageWorkedWith']

languages2019 = []

for row in language2019:
  for lang in str(row).split(';'):
    if lang not in languages2019:
      languages2019.append(lang)
    if lang not in total_languages:
      total_languages.append(lang)
      
print(languages2019)
print(len(languages2019))

['HTML/CSS', 'Java', 'JavaScript', 'Python', 'C++', 'C', 'C#', 'SQL', 'VBA', 'R', 'Bash/Shell/PowerShell', 'Ruby', 'Rust', 'TypeScript', 'WebAssembly', 'Other(s):', 'Go', 'PHP', 'Assembly', 'Kotlin', 'Swift', 'nan', 'Objective-C', 'Elixir', 'Erlang', 'Clojure', 'F#', 'Scala', 'Dart']
29

In [ ]:
language2020 = data2020['LanguageWorkedWith']

languages2020 = []

for row in language2020:
  for lang in str(row).split(';'):
    if lang not in languages2020:
      languages2020.append(lang)
    if lang not in total_languages:
      total_languages.append(lang)
      
print(languages2020)
print(len(languages2020))

['C#', 'HTML/CSS', 'JavaScript', 'Swift', 'Objective-C', 'Python', 'nan', 'Ruby', 'SQL', 'Java', 'PHP', 'C', 'TypeScript', 'Bash/Shell/PowerShell', 'Kotlin', 'R', 'VBA', 'Perl', 'Scala', 'C++', 'Go', 'Haskell', 'Rust', 'Dart', 'Julia', 'Assembly']
26

In [ ]:
lang_overview = {}

print(len(total_languages))

common_languages = []

for lang in total_languages:
  isExist = [0, 0, 0]
  if lang in languages2018:
    isExist[0] = 1
  if lang in languages2019:
    isExist[1] = 1
  if lang in languages2020:
    isExist[2] = 1
  
  if isExist[0] and isExist[1] and isExist[2]:
    common_languages.append(lang)

  lang_overview[lang] = isExist

common_languages.append('HTML')
common_languages.append('CSS')
print(len(common_languages), common_languages)

data = pd.DataFrame(lang_overview).drop('nan', axis=1)
data

45
22 ['JavaScript', 'Python', 'nan', 'C#', 'SQL', 'TypeScript', 'C', 'C++', 'Java', 'R', 'Assembly', 'Go', 'Ruby', 'PHP', 'Swift', 'Kotlin', 'Objective-C', 'Scala', 'Rust', 'VBA', 'HTML', 'CSS']

   JavaScript  Python  HTML  CSS  ...  WebAssembly  Other(s):  Elixir  Dart
0           1       1     1    1  ...            0          0       0     0
1           1       1     0    0  ...            1          1       1     1
2           1       1     0    0  ...            0          0       0     1

[3 rows x 44 columns]

In [ ]:
# process 2018

post_lang2018 = []

for data in language2018:
  row = [0 for _ in common_languages]
  for lang in str(data).split(';'):
    if lang == 'HTML/CSS':
      row[common_languages.index('HTML')] = 1
      row[common_languages.index('CSS')] = 1
    if lang in common_languages:
      row[common_languages.index(lang)] = 1
  post_lang2018.append(row)

data = pd.DataFrame(post_lang2018)
data.columns = common_languages
data = data.drop('nan', axis=1)

final_2018 = pd.concat([final_2018, data],axis=1)
final_2018

       JavaScript  Python  C#  SQL  TypeScript  ...  Scala  Rust  VBA  HTML  CSS
0               1       1   0    0           0  ...      0     0    0     1    1
1               1       1   0    0           0  ...      0     0    0     0    0
2               0       0   0    0           0  ...      0     0    0     0    0
3               1       0   1    1           1  ...      0     0    0     1    1
4               0       0   0    1           0  ...      0     0    0     0    0
...           ...     ...  ..  ...         ...  ...    ...   ...  ...   ...  ...
98850           0       0   0    0           0  ...      0     0    0     0    0
98851           0       0   0    0           0  ...      0     0    0     0    0
98852           0       0   0    0           0  ...      0     0    0     0    0
98853           0       0   0    0           0  ...      0     0    0     0    0
98854           0       0   0    0           0  ...      0     0    0     0    0

[98855 rows x 21 columns]

In [ ]:
# process 2019

post_lang2019 = []

for data in language2019:
  row = [0 for _ in common_languages]
  for lang in str(data).split(';'):
    if lang == 'HTML/CSS':
      row[common_languages.index('HTML')] = 1
      row[common_languages.index('CSS')] = 1
    if lang in common_languages:
      row[common_languages.index(lang)] = 1
  post_lang2019.append(row)

data = pd.DataFrame(post_lang2019)
data.columns = common_languages
data = data.drop('nan', axis=1)

final_2019 = pd.concat([final_2019, data],axis=1)
final_2019

       JavaScript  Python  C#  SQL  TypeScript  ...  Scala  Rust  VBA  HTML  CSS
0               1       1   0    0           0  ...      0     0    0     1    1
1               0       1   0    0           0  ...      0     0    0     1    1
2               0       0   0    0           0  ...      0     0    0     1    1
3               0       1   1    1           0  ...      0     0    0     0    0
4               1       1   0    1           0  ...      0     0    1     1    1
...           ...     ...  ..  ...         ...  ...    ...   ...  ...   ...  ...
88878           1       0   0    0           0  ...      0     0    0     1    1
88879           0       0   0    0           0  ...      0     0    0     0    0
88880           0       0   0    0           0  ...      0     0    0     0    0
88881           0       0   0    0           0  ...      0     0    0     0    0
88882           1       0   0    1           0  ...      0     0    0     1    1

[88883 rows x 21 columns]

In [ ]:
# process 2020

post_lang2020 = []

for data in language2020:
  row = [0 for _ in common_languages]
  for lang in str(data).split(';'):
    if lang == 'HTML/CSS':
      row[common_languages.index('HTML')] = 1
      row[common_languages.index('CSS')] = 1
    if lang in common_languages:
      row[common_languages.index(lang)] = 1
  post_lang2020.append(row)

data = pd.DataFrame(post_lang2020)
data.columns = common_languages
data = data.drop('nan', axis=1)

final_2020 = pd.concat([final_2020, data],axis=1)
final_2020

       JavaScript  Python  C#  SQL  TypeScript  ...  Scala  Rust  VBA  HTML  CSS
0               1       0   1    0           0  ...      0     0    0     1    1
1               1       0   0    0           0  ...      0     0    0     0    0
2               0       1   0    0           0  ...      0     0    0     0    0
3               0       0   0    0           0  ...      0     0    0     0    0
4               0       0   0    1           0  ...      0     0    0     1    1
...           ...     ...  ..  ...         ...  ...    ...   ...  ...   ...  ...
64456           0       0   0    0           0  ...      0     0    0     0    0
64457           1       1   1    1           1  ...      1     1    1     1    1
64458           0       0   0    0           0  ...      0     0    0     0    0
64459           0       0   0    0           0  ...      0     0    0     1    1
64460           1       0   1    1           0  ...      0     0    0     1    1

[64461 rows x 21 columns]

## PlatformWorked With

In [ ]:
total_platforms = []

In [ ]:
platform2018 = data2018['PlatformWorkedWith']

platforms2018 = []

for row in platform2018:
  for lang in str(row).split(';'):
    if lang == 'Mac OS':
      lang = 'MacOS'
    if lang == 'Windows Desktop or Server':
      lang = 'Windows'
    if lang == 'Google Cloud Platform/App Engine':
      lang = 'Google Cloud Platform'
    if lang not in platforms2018:
      platforms2018.append(lang)
    if lang not in total_platforms:
      total_platforms.append(lang)

print(platforms2018)
print(len(platforms2018))

['AWS', 'Azure', 'Linux', 'Firebase', 'nan', 'Arduino', 'Windows', 'Heroku', 'Amazon Echo', 'iOS', 'MacOS', 'Serverless', 'Android', 'WordPress', 'Drupal', 'Google Cloud Platform', 'Raspberry Pi', 'SharePoint', 'IBM Cloud or Watson', 'Mainframe', 'Apple Watch or Apple TV', 'ESP8266', 'Gaming console', 'Predix', 'Windows Phone', 'Salesforce', 'Google Home']
27

In [ ]:
platform2019 = data2019['PlatformWorkedWith']

platforms2019 = []

for row in platform2019:
  for lang in str(row).split(';'):
    if lang not in platforms2019:
      platforms2019.append(lang)
    if lang not in total_platforms:
      total_platforms.append(lang)

print(platforms2019)
print(len(platforms2019))

['MacOS', 'Windows', 'nan', 'Linux', 'Android', 'Slack', 'Google Cloud Platform', 'AWS', 'Docker', 'Heroku', 'IBM Cloud or Watson', 'iOS', 'Microsoft Azure', 'WordPress', 'Arduino', 'Raspberry Pi', 'Kubernetes', 'Other(s):']
18

In [ ]:
platform2020 = data2020['PlatformWorkedWith']

platforms2020 = []

for row in platform2020:
  for lang in str(row).split(';'):
    if lang not in platforms2020:
      platforms2020.append(lang)
    if lang not in total_platforms:
      total_platforms.append(lang)

print(platforms2020)
print(len(platforms2020))

['Windows', 'iOS', 'nan', 'AWS', 'Docker', 'Linux', 'MacOS', 'Android', 'WordPress', 'Raspberry Pi', 'Heroku', 'Google Cloud Platform', 'Kubernetes', 'Arduino', 'Slack Apps and Integrations', 'Microsoft Azure', 'IBM Cloud or Watson']
17

In [ ]:
platform_overview = {}

print(len(total_platforms))

common_platforms = []

for platform in total_platforms:
  isExist = [0, 0, 0]
  if platform in platforms2018:
    isExist[0] = 1
  if platform in platforms2019:
    isExist[1] = 1
  if platform in platforms2020:
    isExist[2] = 1
  
  if isExist[0] and isExist[1] and isExist[2]:
    common_platforms.append(platform)

  platform_overview[platform] = isExist

print(len(common_platforms), common_platforms)

data = pd.DataFrame(platform_overview).drop('nan', axis=1)
data

33
13 ['AWS', 'Linux', 'nan', 'Arduino', 'Windows', 'Heroku', 'iOS', 'MacOS', 'Android', 'WordPress', 'Google Cloud Platform', 'Raspberry Pi', 'IBM Cloud or Watson']

   AWS  Azure  Linux  ...  Kubernetes  Other(s):  Slack Apps and Integrations
0    1      1      1  ...           0          0                            0
1    1      0      1  ...           1          1                            0
2    1      0      1  ...           1          0                            1

[3 rows x 32 columns]

In [ ]:
# process 2018
post_platform2018 = []

for data in platform2018:
  row = [0 for _ in common_platforms]
  for lang in str(data).split(';'):
    if lang in common_platforms:
      row[common_platforms.index(lang)] = 1
  post_platform2018.append(row)

data = pd.DataFrame(post_platform2018)
data.columns = common_platforms
data = data.drop('nan', axis=1)

final_2018 = pd.concat([final_2018, data],axis=1)
final_2018

# process 2019
post_platform2019 = []

for data in platform2019:
  row = [0 for _ in common_platforms]
  for lang in str(data).split(';'):
    if lang in common_platforms:
      row[common_platforms.index(lang)] = 1
  post_platform2019.append(row)

data = pd.DataFrame(post_platform2019)
data.columns = common_platforms
data = data.drop('nan', axis=1)
final_2019 = pd.concat([final_2019, data],axis=1)
final_2019

# process 2020
post_platform2020 = []

for data in platform2020:
  row = [0 for _ in common_platforms]
  for lang in str(data).split(';'):
    if lang in common_platforms:
      row[common_platforms.index(lang)] = 1
  post_platform2020.append(row)

data = pd.DataFrame(post_platform2020)
data.columns = common_platforms
data = data.drop('nan', axis=1)

final_2020 = pd.concat([final_2020, data],axis=1)
final_2020

       JavaScript  Python  ...  Raspberry Pi  IBM Cloud or Watson
0               1       0  ...             0                    0
1               1       0  ...             0                    0
2               0       1  ...             0                    0
3               0       0  ...             0                    0
4               0       0  ...             0                    0
...           ...     ...  ...           ...                  ...
64456           0       0  ...             0                    0
64457           1       1  ...             0                    0
64458           0       0  ...             0                    0
64459           0       0  ...             0                    0
64460           1       0  ...             1                    0

[64461 rows x 33 columns]

## DatabaseWorkedWith

In [ ]:
total_databases = []

# 2018
database2018 = data2018['DatabaseWorkedWith']

databases2018 = []

for row in database2018:
  for lang in str(row).split(';'):
    if lang not in databases2018:
      databases2018.append(lang)
    if lang not in total_databases:
      total_databases.append(lang)

print(databases2018)
print(len(databases2018))

# 2019
database2019 = data2019['DatabaseWorkedWith']

databases2019 = []

for row in database2019:
  for lang in str(row).split(';'):
    if lang not in databases2019:
      databases2019.append(lang)
    if lang not in total_databases:
      total_databases.append(lang)

print(databases2019)
print(len(databases2019))

# 2020
database2020 = data2020['DatabaseWorkedWith']

databases2020 = []

for row in database2020:
  for lang in str(row).split(';'):
    if lang not in databases2020:
      databases2020.append(lang)
    if lang not in total_databases:
      total_databases.append(lang)

print(databases2020)
print(len(databases2020))

['Redis', 'SQL Server', 'MySQL', 'PostgreSQL', 'Amazon RDS/Aurora', 'Microsoft Azure (Tables, CosmosDB, SQL, etc)', 'Memcached', 'nan', 'Oracle', 'IBM Db2', 'MongoDB', 'Google Cloud Storage', 'Amazon DynamoDB', 'Apache HBase', 'Apache Hive', 'Amazon Redshift', 'Elasticsearch', 'MariaDB', 'SQLite', 'Google BigQuery', 'Cassandra', 'Neo4j']
22
['SQLite', 'nan', 'PostgreSQL', 'MySQL', 'Couchbase', 'MongoDB', 'Oracle', 'Cassandra', 'Elasticsearch', 'Redis', 'DynamoDB', 'Microsoft SQL Server', 'Firebase', 'MariaDB', 'Other(s):']
15
['Elasticsearch', 'Microsoft SQL Server', 'Oracle', 'nan', 'MySQL', 'PostgreSQL', 'Redis', 'SQLite', 'MariaDB', 'Firebase', 'MongoDB', 'IBM DB2', 'DynamoDB', 'Cassandra', 'Couchbase']
15

In [ ]:
database_overview = {}

print(len(total_databases))

common_databases = []

for database in total_databases:
  isExist = [0, 0, 0]
  if database in databases2018:
    isExist[0] = 1
  if database in databases2019:
    isExist[1] = 1
  if database in databases2020:
    isExist[2] = 1
  
  if isExist[0] and isExist[1] and isExist[2]:
    common_databases.append(database)

  database_overview[database] = isExist

print(len(common_databases), common_databases)

data = pd.DataFrame(database_overview).drop('nan', axis=1)
data

28
10 ['Redis', 'MySQL', 'PostgreSQL', 'nan', 'Oracle', 'MongoDB', 'Elasticsearch', 'MariaDB', 'SQLite', 'Cassandra']

   Redis  SQL Server  MySQL  ...  Firebase  Other(s):  IBM DB2
0      1           1      1  ...         0          0        0
1      1           0      1  ...         1          1        0
2      1           0      1  ...         1          0        1

[3 rows x 27 columns]

In [ ]:
# process 2018
post_database2018 = []

for data in database2018:
  row = [0 for _ in common_databases]
  for lang in str(data).split(';'):
    if lang in common_databases:
      row[common_databases.index(lang)] = 1
  post_database2018.append(row)

data = pd.DataFrame(post_database2018)
data.columns = common_databases
data = data.drop('nan', axis=1)

final_2018 = pd.concat([final_2018, data],axis=1)
final_2018

# process 2019
post_database2019 = []

for data in database2019:
  row = [0 for _ in common_databases]
  for lang in str(data).split(';'):
    if lang in common_databases:
      row[common_databases.index(lang)] = 1
  post_database2019.append(row)

data = pd.DataFrame(post_database2019)
data.columns = common_databases
data = data.drop('nan', axis=1)

final_2019 = pd.concat([final_2019, data],axis=1)
final_2019

# process 2020
post_database2020 = []

for data in database2020:
  row = [0 for _ in common_databases]
  for lang in str(data).split(';'):
    if lang in common_databases:
      row[common_databases.index(lang)] = 1
  post_database2020.append(row)

data = pd.DataFrame(post_database2020)
data.columns = common_databases
data = data.drop('nan', axis=1)

final_2020 = pd.concat([final_2020, data],axis=1)
final_2020

       JavaScript  Python  C#  SQL  ...  Elasticsearch  MariaDB  SQLite  Cassandra
0               1       0   1    0  ...              1        0       0          0
1               1       0   0    0  ...              0        0       0          0
2               0       1   0    0  ...              0        0       0          0
3               0       0   0    0  ...              0        0       0          0
4               0       0   0    1  ...              0        0       1          0
...           ...     ...  ..  ...  ...            ...      ...     ...        ...
64456           0       0   0    0  ...              0        0       0          0
64457           1       1   1    1  ...              1        1       1          1
64458           0       0   0    0  ...              0        0       0          0
64459           0       0   0    0  ...              0        0       0          0
64460           1       0   1    1  ...              0        1       0          0

[64461 rows x 42 columns]

## WebFrameWorkedWith + MiscTechWorkedWith

*2018년도의 "FrameworkWorkedWith"  = 2019 & 2020 년도의 "WebFrameWorkedWith" + "MiscTechWorkedWith"

In [ ]:
total_MiscTech = []

# 2018
miscTech2018 = data2018['FrameworkWorkedWith']

MiscTech2018 = []

for row in miscTech2018:
  for lang in str(row).split(';'):
    if lang not in MiscTech2018:
      MiscTech2018.append(lang)
    if lang not in total_MiscTech:
      total_MiscTech.append(lang)

print(MiscTech2018)
print(len(MiscTech2018))

# 2019
webFrame2019 = data2019['WebFrameWorkedWith']
miscTech2019 = data2019['MiscTechWorkedWith']
merged2019 = []

for i in range(len(webFrame2019)):
  merged2019.append(str(webFrame2019[i]) + ';' + str(miscTech2019[i]))

MiscTech2019 = []

for row in merged2019:
  for lang in str(row).split(';'):
    if lang not in MiscTech2019:
      MiscTech2019.append(lang)
    if lang not in total_MiscTech:
      total_MiscTech.append(lang)

print(MiscTech2019)
print(len(MiscTech2019))

# 2020
webFrame2020 = data2020['WebframeWorkedWith']
miscTech2020 = data2020['MiscTechWorkedWith']
merged2020 = []

for i in range(len(webFrame2020)):
  merged2020.append(str(webFrame2020[i]) + ';' + str(miscTech2020[i]))

MiscTech2020 = []

for row in merged2020:
  for lang in str(row).split(';'):
    if lang not in MiscTech2020:
      MiscTech2020.append(lang)
    if lang not in total_MiscTech:
      total_MiscTech.append(lang)

print(MiscTech2020)
print(len(MiscTech2020))

['Django', 'React', 'nan', 'Angular', 'Node.js', 'Hadoop', 'Spark', 'Spring', '.NET Core', 'Cordova', 'Xamarin', 'TensorFlow', 'Torch/PyTorch']
13
['Django', 'Flask', 'Node.js', 'nan', '.NET', 'Express', 'jQuery', 'React.js', 'Spring', 'Cordova', 'Hadoop', 'Pandas', 'Ruby on Rails', 'Other(s):', 'Unity 3D', 'Angular/Angular.js', 'ASP.NET', 'Torch/PyTorch', 'Ansible', 'Chef', 'TensorFlow', 'Vue.js', 'Xamarin', '.NET Core', 'Laravel', 'Drupal', 'React Native', 'Puppet', 'Apache Spark', 'Unreal Engine', 'Flutter', 'CryEngine']
32
['ASP.NET', 'ASP.NET Core', '.NET', '.NET Core', 'nan', 'React Native', 'Ruby on Rails', 'Ansible', 'Flask', 'jQuery', 'Pandas', 'Angular', 'Angular.js', 'Django', 'React.js', 'Node.js', 'Vue.js', 'Gatsby', 'Spring', 'Express', 'Unity 3D', 'TensorFlow', 'Torch/PyTorch', 'Teraform', 'Unreal Engine', 'Hadoop', 'Flutter', 'Cordova', 'Symfony', 'Laravel', 'Xamarin', 'Keras', 'Chef', 'Apache Spark', 'Drupal', 'Puppet']
36

In [ ]:
mistTech_overview = {}

print(len(total_MiscTech))

common_mistTechs = []

for mistTech in total_MiscTech:
  isExist = [0, 0, 0]
  if mistTech in MiscTech2018:
    isExist[0] = 1
  if mistTech in MiscTech2019:
    isExist[1] = 1
  if mistTech in MiscTech2020:
    isExist[2] = 1
  
  if isExist[0] and isExist[1] and isExist[2]:
    common_mistTechs.append(mistTech)

  mistTech_overview[mistTech] = isExist

print(len(common_mistTechs), common_mistTechs)

data = pd.DataFrame(mistTech_overview).drop('nan', axis=1)
data

41
10 ['Django', 'nan', 'Node.js', 'Hadoop', 'Spring', '.NET Core', 'Cordova', 'Xamarin', 'TensorFlow', 'Torch/PyTorch']

   Django  React  Angular  Node.js  ...  Gatsby  Teraform  Symfony  Keras
0       1      1        1        1  ...       0         0        0      0
1       1      0        0        1  ...       0         0        0      0
2       1      0        1        1  ...       1         1        1      1

[3 rows x 40 columns]

In [ ]:
# process 2018
post_misTech2018 = []

for data in miscTech2018:
  row = [0 for _ in common_mistTechs]
  for lang in str(data).split(';'):
    if lang in common_mistTechs:
      row[common_mistTechs.index(lang)] = 1
  post_misTech2018.append(row)

data = pd.DataFrame(post_misTech2018)
data.columns = common_mistTechs
data = data.drop('nan', axis=1)
final_2018 = pd.concat([final_2018, data],axis=1)
final_2018

# process 2019
post_misTech2019 = []

for data in merged2019:
  row = [0 for _ in common_mistTechs]
  for lang in str(data).split(';'):
    if lang in common_mistTechs:
      row[common_mistTechs.index(lang)] = 1
  post_misTech2019.append(row)

data = pd.DataFrame(post_misTech2019)
data.columns = common_mistTechs
data = data.drop('nan', axis=1)
final_2019 = pd.concat([final_2019, data],axis=1)
final_2019

# process 2020
post_misTech2020 = []

for data in merged2020:
  row = [0 for _ in common_mistTechs]
  for lang in str(data).split(';'):
    if lang in common_mistTechs:
      row[common_mistTechs.index(lang)] = 1
  post_misTech2020.append(row)

data = pd.DataFrame(post_misTech2020)
data.columns = common_mistTechs
data = data.drop('nan', axis=1)
final_2020 = pd.concat([final_2020, data],axis=1)
final_2020

       JavaScript  Python  C#  SQL  ...  Cordova  Xamarin  TensorFlow  Torch/PyTorch
0               1       0   1    0  ...        0        0           0              0
1               1       0   0    0  ...        0        0           0              0
2               0       1   0    0  ...        0        0           0              0
3               0       0   0    0  ...        0        0           0              0
4               0       0   0    1  ...        0        0           0              0
...           ...     ...  ..  ...  ...      ...      ...         ...            ...
64456           0       0   0    0  ...        0        0           0              0
64457           1       1   1    1  ...        0        0           0              0
64458           0       0   0    0  ...        0        0           0              0
64459           0       0   0    0  ...        0        0           0              0
64460           1       0   1    1  ...        0        0           0              0

[64461 rows x 51 columns]

In [ ]:
final_2020.head()

   JavaScript  Python  C#  SQL  ...  Cordova  Xamarin  TensorFlow  Torch/PyTorch
0           1       0   1    0  ...        0        0           0              0
1           1       0   0    0  ...        0        0           0              0
2           0       1   0    0  ...        0        0           0              0
3           0       0   0    0  ...        0        0           0              0
4           0       0   0    1  ...        0        0           0              0

[5 rows x 51 columns]

## Save to CSV

In [ ]:
final_2020.columns

Index(['JavaScript', 'Python', 'C#', 'SQL', 'TypeScript', 'C', 'C++', 'Java',
       'R', 'Assembly', 'Go', 'Ruby', 'PHP', 'Swift', 'Kotlin', 'Objective-C',
       'Scala', 'Rust', 'VBA', 'HTML', 'CSS', 'AWS', 'Linux', 'Arduino',
       'Windows', 'Heroku', 'iOS', 'MacOS', 'Android', 'WordPress',
       'Google Cloud Platform', 'Raspberry Pi', 'IBM Cloud or Watson', 'Redis',
       'MySQL', 'PostgreSQL', 'Oracle', 'MongoDB', 'Elasticsearch', 'MariaDB',
       'SQLite', 'Cassandra', 'Django', 'Node.js', 'Hadoop', 'Spring',
       '.NET Core', 'Cordova', 'Xamarin', 'TensorFlow', 'Torch/PyTorch'],
      dtype='object')

In [ ]:
permute_columns = ['year'] + list(final_2020.columns)
permute_columns

['year',
 'JavaScript',
 'Python',
 'C#',
 'SQL',
 'TypeScript',
 'C',
 'C++',
 'Java',
 'R',
 'Assembly',
 'Go',
 'Ruby',
 'PHP',
 'Swift',
 'Kotlin',
 'Objective-C',
 'Scala',
 'Rust',
 'VBA',
 'HTML',
 'CSS',
 'AWS',
 'Linux',
 'Arduino',
 'Windows',
 'Heroku',
 'iOS',
 'MacOS',
 'Android',
 'WordPress',
 'Google Cloud Platform',
 'Raspberry Pi',
 'IBM Cloud or Watson',
 'Redis',
 'MySQL',
 'PostgreSQL',
 'Oracle',
 'MongoDB',
 'Elasticsearch',
 'MariaDB',
 'SQLite',
 'Cassandra',
 'Django',
 'Node.js',
 'Hadoop',
 'Spring',
 '.NET Core',
 'Cordova',
 'Xamarin',
 'TensorFlow',
 'Torch/PyTorch']

In [ ]:
final_2018['year'] = 2018
final_2018 = final_2018[permute_columns]
final_2019['year'] = 2019
final_2019 = final_2019[permute_columns]
final_2020['year'] = 2020
final_2020 = final_2020[permute_columns]
final_2018

       year  JavaScript  Python  ...  Xamarin  TensorFlow  Torch/PyTorch
0      2018           1       1  ...        0           0              0
1      2018           1       1  ...        0           0              0
2      2018           0       0  ...        0           0              0
3      2018           1       0  ...        0           0              0
4      2018           0       0  ...        0           0              0
...     ...         ...     ...  ...      ...         ...            ...
98850  2018           0       0  ...        0           0              0
98851  2018           0       0  ...        0           0              0
98852  2018           0       0  ...        0           0              0
98853  2018           0       0  ...        0           0              0
98854  2018           0       0  ...        0           0              0

[98855 rows x 52 columns]

In [ ]:
final_2018.to_csv('skills_2018.csv', index=False, encoding='cp949')
final_2019.to_csv('skills_2019.csv', index=False, encoding='cp949')
final_2020.to_csv('skills_2020.csv', index=False, encoding='cp949')

In [ ]:
final_total = pd.concat([final_2018, final_2019, final_2020])

In [ ]:
print(len(final_2018), len(final_2019), len(final_2020))
print(len(final_total))
final_total

98855 88883 64461
252199

       year  JavaScript  Python  ...  Xamarin  TensorFlow  Torch/PyTorch
0      2018           1       1  ...        0           0              0
1      2018           1       1  ...        0           0              0
2      2018           0       0  ...        0           0              0
3      2018           1       0  ...        0           0              0
4      2018           0       0  ...        0           0              0
...     ...         ...     ...  ...      ...         ...            ...
64456  2020           0       0  ...        0           0              0
64457  2020           1       1  ...        0           0              0
64458  2020           0       0  ...        0           0              0
64459  2020           0       0  ...        0           0              0
64460  2020           1       0  ...        0           0              0

[252199 rows x 52 columns]

In [ ]:
final_total.to_csv('skills_total.csv', index=False, encoding='cp949')

# Prev works

In [ ]:
commonFeatures = []
twoFeatures = []
only2020 = []
only2019 = []
only2018 = []

for key in columns:
  length = len(columns[key])
  if length == 3:
    commonFeatures.append(key)
  elif length == 2:
    twoFeatures.append(key)
  else:
    if columns[key][0] == '2020':
      only2020.append(key)
    elif columns[key][0] == '2019':
      only2019.append(key)
    else:
      only2018.append(key)

print("======= common in 2020, 2019, 2018 =======")
print("length is", len(commonFeatures))
print(commonFeatures)

print("======= common in two years ======")
print("length is", len(twoFeatures))
print(twoFeatures)

print("======= only in 2020 =======")
print("length is", len(only2020))
print(only2020)

print("======= only in 2019 =======")
print("length is", len(only2019))
print(only2019)

print("======= only in 2028 =======")
print("length is", len(only2018))
print(only2018)

======= common in 2020, 2019, 2018 =======
length is 20
['Respondent', 'Hobbyist', 'Age', 'Country', 'CurrencySymbol', 'DatabaseDesireNextYear', 'DatabaseWorkedWith', 'DevType', 'EdLevel', 'Employment', 'Ethnicity', 'Gender', 'JobSat', 'LanguageDesireNextYear', 'LanguageWorkedWith', 'OrgSize', 'PlatformDesireNextYear', 'PlatformWorkedWith', 'UndergradMajor', 'YearsCode']
======= common in two years ======
length is 26
['MainBranch', 'Age1stCode', 'CompFreq', 'CompTotal', 'ConvertedComp', 'CurrencyDesc', 'JobFactors', 'JobSeek', 'MiscTechDesireNextYear', 'MiscTechWorkedWith', 'OpSys', 'PurchaseWhat', 'Sexuality', 'SOAccount', 'SOComm', 'SOPartFreq', 'SOVisitFreq', 'SurveyEase', 'SurveyLength', 'Trans', 'WelcomeChange', 'WorkWeekHrs', 'YearsCodePro', 'OpenSource', 'Student', 'Dependents']
======= only in 2020 =======
length is 18
['NEWCollabToolsDesireNextYear', 'NEWCollabToolsWorkedWith', 'NEWDevOps', 'NEWDevOpsImpt', 'NEWEdImpt', 'NEWJobHunt', 'NEWJobHuntResearch', 'NEWLearn', 'NEWOffTopic', 'NEWOnboardGood', 'NEWOtherComms', 'NEWOvertime', 'NEWPurchaseResearch', 'NEWPurpleLink', 'NEWSOSites', 'NEWStuck', 'WebframeDesireNextYear', 'WebframeWorkedWith']
======= only in 2019 =======
length is 39
['OpenSourcer', 'EduOther', 'CareerSat', 'MgrIdiot', 'MgrMoney', 'MgrWant', 'LastHireDate', 'LastInt', 'FizzBuzz', 'ResumeUpdate', 'WorkPlan', 'WorkChallenge', 'WorkRemote', 'WorkLoc', 'ImpSyn', 'CodeRev', 'CodeRevHrs', 'UnitTests', 'PurchaseHow', 'WebFrameWorkedWith', 'WebFrameDesireNextYear', 'DevEnviron', 'Containers', 'BlockchainOrg', 'BlockchainIs', 'BetterLife', 'ITperson', 'OffOn', 'SocialMedia', 'Extraversion', 'ScreenName', 'SOVisit1st', 'SOVisitTo', 'SOFindAnswer', 'SOTimeSaved', 'SOHowMuchTime', 'SOJobs', 'EntTeams', 'SONewContent']
======= only in 2028 =======
length is 106
['YearsCodingProf', 'CareerSatisfaction', 'HopeFiveYears', 'JobSeek ', 'LastNewJob', 'AssessJob1', 'AssessJob2', 'AssessJob3', 'AssessJob4', 'AssessJob5', 'AssessJob6', 'AssessJob7', 'AssessJob8', 'AssessJob9', 'AssessJob10', 'AssessBenefits1', 'AssessBenefits2', 'AssessBenefits3', 'AssessBenefits4', 'AssessBenefits5', 'AssessBenefits6', 'AssessBenefits7', 'AssessBenefits8', 'AssessBenefits9', 'AssessBenefits10', 'AssessBenefits11', 'JobContactPriorities1', 'JobContactPriorities2', 'JobContactPriorities3', 'JobContactPriorities4', 'JobContactPriorities5', 'JobEmailPriorities1', 'JobEmailPriorities2', 'JobEmailPriorities3', 'JobEmailPriorities4', 'JobEmailPriorities5', 'JobEmailPriorities6', 'JobEmailPriorities7', 'UpdateCV', 'Currency', 'Salary', 'SalaryType', 'ConvertedSalary', 'CommunicationTools', 'TimeFullyProductive', 'EducationTypes', 'SelfTaughtTypes', 'TimeAfterBootcamp', 'HackathonReasons', 'AgreeDisagree1', 'AgreeDisagree2', 'AgreeDisagree3', 'FrameworkWorkedWith', 'FrameworkDesireNextYear', 'IDE', 'OpSys ', 'NumberMonitors', 'Methodology', 'VersionControl', 'CheckInCode', 'AdBlocker', 'AdBlockerDisable', 'AdBlockerReasons', 'AdsAgreeDisagree1', 'AdsAgreeDisagree2', 'AdsAgreeDisagree3', 'AdsActions', 'AdsPriorities1', 'AdsPriorities2', 'AdsPriorities3', 'AdsPriorities4', 'AdsPriorities5', 'AdsPriorities6', 'AdsPriorities7', 'AIDangerous', 'AIInteresting', 'AIResponsible', 'AIFuture', 'EthicsChoice', 'EthicsReport', 'EthicsResponsible', 'EthicalImplications', 'StackOverflowRecommend', 'StackOverflowVisit', 'StackOverflowHasAccount', 'StackOverflowParticipate', 'StackOverflowJobs', 'StackOverflowDevStory', 'StackOverflowJobsRecommend', 'StackOverflowConsiderMember', 'HypotheticalTools1', 'HypotheticalTools2', 'HypotheticalTools3', 'HypotheticalTools4', 'HypotheticalTools5', 'WakeTime', 'HoursComputer', 'HoursOutside', 'SkipMeals', 'ErgonomicDevices', 'Exercise', 'SexualOrientation', 'EducationParents', 'MilitaryUS', 'SurveyTooLong', 'SurveyEasy']

In [ ]:
query_key = "FormalEducation"
# print(data2020[query_key].head())
print(data2019["OpSys"].head())
print(data2018["OperatingSystem"].head())

0        Windows
1        Windows
2    Linux-based
3        Windows
4    Linux-based
Name: OpSys, dtype: object
0    Linux-based
1    Linux-based
2            NaN
3        Windows
4        Windows
Name: OperatingSystem, dtype: object

In [ ]:
data2018[only2018].head()

# for key in columns2018:
  # print(key)

                                     FormalEducation  ...     SurveyEasy
0           Bachelor’s degree (BA, BS, B.Eng., etc.)  ...      Very easy
1           Bachelor’s degree (BA, BS, B.Eng., etc.)  ...  Somewhat easy
2                                   Associate degree  ...            NaN
3           Bachelor’s degree (BA, BS, B.Eng., etc.)  ...  Somewhat easy
4  Some college/university study without earning ...  ...  Somewhat easy

[5 rows x 111 columns]

In [ ]:
columns = {}
for key in columns2020:
  columns[key] = ['2020']
for key in columns2019:
  if key in columns:
    columns[key].append('2019')
  else:
    columns[key] = ['2019']
for key in columns2018:
  if key in columns:
    columns[key].append('2018')
  else:
    columns[key] = ['2018']

for key in columns:
  print(key, columns[key])

Respondent ['2020', '2019', '2018']
MainBranch ['2020', '2019']
Hobbyist ['2020', '2019', '2018']
Age ['2020', '2019', '2018']
Age1stCode ['2020', '2019']
CompFreq ['2020', '2019']
CompTotal ['2020', '2019']
ConvertedComp ['2020', '2019']
Country ['2020', '2019', '2018']
CurrencyDesc ['2020', '2019']
CurrencySymbol ['2020', '2019', '2018']
DatabaseDesireNextYear ['2020', '2019', '2018']
DatabaseWorkedWith ['2020', '2019', '2018']
DevType ['2020', '2019', '2018']
EdLevel ['2020', '2019', '2018']
Employment ['2020', '2019', '2018']
Ethnicity ['2020', '2019', '2018']
Gender ['2020', '2019', '2018']
JobFactors ['2020', '2019']
JobSat ['2020', '2019', '2018']
JobSeek ['2020', '2019']
LanguageDesireNextYear ['2020', '2019', '2018']
LanguageWorkedWith ['2020', '2019', '2018']
MiscTechDesireNextYear ['2020', '2019']
MiscTechWorkedWith ['2020', '2019']
NEWCollabToolsDesireNextYear ['2020']
NEWCollabToolsWorkedWith ['2020']
NEWDevOps ['2020']
NEWDevOpsImpt ['2020']
NEWEdImpt ['2020']
NEWJobHunt ['2020']
NEWJobHuntResearch ['2020']
NEWLearn ['2020']
NEWOffTopic ['2020']
NEWOnboardGood ['2020']
NEWOtherComms ['2020']
NEWOvertime ['2020']
NEWPurchaseResearch ['2020']
NEWPurpleLink ['2020']
NEWSOSites ['2020']
NEWStuck ['2020']
OpSys ['2020', '2019']
OrgSize ['2020', '2019', '2018']
PlatformDesireNextYear ['2020', '2019', '2018']
PlatformWorkedWith ['2020', '2019', '2018']
PurchaseWhat ['2020', '2019']
Sexuality ['2020', '2019']
SOAccount ['2020', '2019']
SOComm ['2020', '2019']
SOPartFreq ['2020', '2019']
SOVisitFreq ['2020', '2019']
SurveyEase ['2020', '2019']
SurveyLength ['2020', '2019']
Trans ['2020', '2019']
UndergradMajor ['2020', '2019', '2018']
WebframeDesireNextYear ['2020']
WebframeWorkedWith ['2020']
WelcomeChange ['2020', '2019']
WorkWeekHrs ['2020', '2019']
YearsCode ['2020', '2019', '2018']
YearsCodePro ['2020', '2019']
OpenSourcer ['2019']
OpenSource ['2019', '2018']
Student ['2019', '2018']
EduOther ['2019']
CareerSat ['2019']
MgrIdiot ['2019']
MgrMoney ['2019']
MgrWant ['2019']
LastHireDate ['2019']
LastInt ['2019']
FizzBuzz ['2019']
ResumeUpdate ['2019']
WorkPlan ['2019']
WorkChallenge ['2019']
WorkRemote ['2019']
WorkLoc ['2019']
ImpSyn ['2019']
CodeRev ['2019']
CodeRevHrs ['2019']
UnitTests ['2019']
PurchaseHow ['2019']
WebFrameWorkedWith ['2019']
WebFrameDesireNextYear ['2019']
DevEnviron ['2019']
Containers ['2019']
BlockchainOrg ['2019']
BlockchainIs ['2019']
BetterLife ['2019']
ITperson ['2019']
OffOn ['2019']
SocialMedia ['2019']
Extraversion ['2019']
ScreenName ['2019']
SOVisit1st ['2019']
SOVisitTo ['2019']
SOFindAnswer ['2019']
SOTimeSaved ['2019']
SOHowMuchTime ['2019']
SOJobs ['2019']
EntTeams ['2019']
SONewContent ['2019']
Dependents ['2019', '2018']
YearsCodingProf ['2018']
CareerSatisfaction ['2018']
HopeFiveYears ['2018']
JobSeek  ['2018']
LastNewJob ['2018']
AssessJob1 ['2018']
AssessJob2 ['2018']
AssessJob3 ['2018']
AssessJob4 ['2018']
AssessJob5 ['2018']
AssessJob6 ['2018']
AssessJob7 ['2018']
AssessJob8 ['2018']
AssessJob9 ['2018']
AssessJob10 ['2018']
AssessBenefits1 ['2018']
AssessBenefits2 ['2018']
AssessBenefits3 ['2018']
AssessBenefits4 ['2018']
AssessBenefits5 ['2018']
AssessBenefits6 ['2018']
AssessBenefits7 ['2018']
AssessBenefits8 ['2018']
AssessBenefits9 ['2018']
AssessBenefits10 ['2018']
AssessBenefits11 ['2018']
JobContactPriorities1 ['2018']
JobContactPriorities2 ['2018']
JobContactPriorities3 ['2018']
JobContactPriorities4 ['2018']
JobContactPriorities5 ['2018']
JobEmailPriorities1 ['2018']
JobEmailPriorities2 ['2018']
JobEmailPriorities3 ['2018']
JobEmailPriorities4 ['2018']
JobEmailPriorities5 ['2018']
JobEmailPriorities6 ['2018']
JobEmailPriorities7 ['2018']
UpdateCV ['2018']
Currency ['2018']
Salary ['2018']
SalaryType ['2018']
ConvertedSalary ['2018']
CommunicationTools ['2018']
TimeFullyProductive ['2018']
EducationTypes ['2018']
SelfTaughtTypes ['2018']
TimeAfterBootcamp ['2018']
HackathonReasons ['2018']
AgreeDisagree1 ['2018']
AgreeDisagree2 ['2018']
AgreeDisagree3 ['2018']
FrameworkWorkedWith ['2018']
FrameworkDesireNextYear ['2018']
IDE ['2018']
OpSys  ['2018']
NumberMonitors ['2018']
Methodology ['2018']
VersionControl ['2018']
CheckInCode ['2018']
AdBlocker ['2018']
AdBlockerDisable ['2018']
AdBlockerReasons ['2018']
AdsAgreeDisagree1 ['2018']
AdsAgreeDisagree2 ['2018']
AdsAgreeDisagree3 ['2018']
AdsActions ['2018']
AdsPriorities1 ['2018']
AdsPriorities2 ['2018']
AdsPriorities3 ['2018']
AdsPriorities4 ['2018']
AdsPriorities5 ['2018']
AdsPriorities6 ['2018']
AdsPriorities7 ['2018']
AIDangerous ['2018']
AIInteresting ['2018']
AIResponsible ['2018']
AIFuture ['2018']
EthicsChoice ['2018']
EthicsReport ['2018']
EthicsResponsible ['2018']
EthicalImplications ['2018']
StackOverflowRecommend ['2018']
StackOverflowVisit ['2018']
StackOverflowHasAccount ['2018']
StackOverflowParticipate ['2018']
StackOverflowJobs ['2018']
StackOverflowDevStory ['2018']
StackOverflowJobsRecommend ['2018']
StackOverflowConsiderMember ['2018']
HypotheticalTools1 ['2018']
HypotheticalTools2 ['2018']
HypotheticalTools3 ['2018']
HypotheticalTools4 ['2018']
HypotheticalTools5 ['2018']
WakeTime ['2018']
HoursComputer ['2018']
HoursOutside ['2018']
SkipMeals ['2018']
ErgonomicDevices ['2018']
Exercise ['2018']
SexualOrientation ['2018']
EducationParents ['2018']
MilitaryUS ['2018']
SurveyTooLong ['2018']
SurveyEasy ['2018']